name: coverage

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.2, 8.3]
                laravel: ['10.*', '11.*', '12.*']
                stability: [prefer-stable]

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, xdebug
                  coverage: xdebug

            - name: Install dependencies
              run: |
                  composer require "illuminate/contracts:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction
            - name: Execute tests
              run: XDEBUG_MODE=coverage php vendor/bin/pest --coverage --min=100
